AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: disable
  Exclude:
    - 'lib/external_plugins/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/BlockNesting:
  Max: 4

Metrics/PerceivedComplexity:
  Max: 12

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: [$shutdown, $restart, $version]

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/NegatedIf:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - lib/plugins/**/spec/*

Layout/EndOfLine:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
