# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  ENV['TEST'] = 'true'

  # Loads .rb patches intended to be run only once.
  patch_dir = File.join(Dir.pwd, 'lib', 'patches')
  Dir.foreach(patch_dir) do |filename|
    if File.extname(filename) == '.rb'
      puts "Loading patch file: #{filename}"
      load File.join(patch_dir, filename)
    end
  end

  require 'eventmachine'

  # Helper method for easier setup/teardown of eventmachine context
  # We setup the bot for each spec as the bot expects to be run in EM as
  # running every spec within a single EM sounds like a terrible idea.
  def with_em(&block)
    EM.run do
      block.call
      EM.stop
    end
  end

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end